version: '3.9'

services:
  authentication-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1
