version: '3'

services:
  authentication-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
